### PR TITLE
refactor: rework internals and external api

### PR DESCRIPTION
**Pull request by varl**
> Replaces: #151 
>
> tl;dr: Lefthook is a promising project but is not mature enough to be used as a base. Husky on the other hand is mature and also much more concise.

## Simpler development

Compare the files in tools:

- `src/tools/js/prettier.js` with the replacement `src/tools/prettier.js`.
- `src/tools/js/eslint.js` with `src/tools/eslint.js`.

Adding new tools in the same style is trivial, where before we relied on NodeJS API bindings to wrangle everything to how we wanted it internally.

The new structure is a lot easier to grok:

```
src/
├── commands
│   ├── commit.js
│   ├── install.js
│   ├── javascript.js
│   └── structured-text.js
├── commands.js
├── index.js
├── tools
│   ├── commitlint.js
│   ├── eslint.js
│   └── prettier.js
└── utils
    ├── config.js
    ├── files.js
    ├── groups.js
    ├── paths.js
    └── run.js
```

### Structured text

Use Prettier to check/apply format rules for various types of structured text:

```
d2-style structured-text check
```

### `project/react` Setup

Generate ESLint configuration for a React project:

```
d2-style setup project/react
```

### ESLint config includes recommended rules

We tried working from bottom-up principles in previous versions, adding more rules as we found them useful, but that work has died off and multiple repos are now (probably wisely) adding `eslint:recommended` to the `.eslintrc.js` configuration file. This centralises and adds it together with the `eslint-config-prettier` to avoid any conflicts between the two.

### CODE REVIEW

**Comment by varl** [comment]
One drawback of not using the straight NodeJS APIs and using `npx` to resolve where the nearest `node_modules/.bin` is that it doesn't work great with monorepos.

It works fine from the root package level, so maybe we can fix the `cwd` for `npx` to that, and ensure it resolves correctly.

**Comment by varl** [comment]
_Ping_ @amcgee since you said on Slack that you would test this.

_Ping_ @Mohammer5 since you originally wanted `lint-staged` added to support committing hunks without getting them clobbered and this version removes `lint-staged` because of the workflow changes.

`cli-style` moves away from automatically reformatting your code when committing to only checking if it is correctly formatted, moving the control of when and what to re-format to the user. It still checks staged files on commit by default, and it is up to the user to handle e.g. stashing and popping changes before/after commits.

I've been running this on multiple repos locally of the last two weeks to try it out. I'm at a point where I am happy with it and come to prefer this less aggressive approach.

I would like to get it in so if you have a chance to look at it that would be great.

image

**Comment by Mohammer5** [comment]
I'm wondering: What was the reason to remove lint-staged and automatic formatting from the workflow? Was it broken or unreliable? Did people complain? Or does it simply not fit into the new architecture and workflow you came up with so it was a "necessary" downgrade?

Other than that this looks pretty solid to me.

**Comment by varl** [comment]
> I'm wondering: What was the reason to remove lint-staged and automatic formatting from the workflow?

Good question. Generally speaking it doesn't have a lot to do with `lint-staged` itself as a technology (except for a few API decisions it forces) and more to do with the consequences it has. I'll go into more detail about that below. First the softer stuff.

#### Feedback

> Did people complain? 

Yes, I have received feedback that always applying the code style and automatically adding the formatted code back to the staged area is feedback. I think it generally always works and does the right thing though, it's just a turn-off for some developers.

> Was it broken or unreliable?

It was _almost_ always reliable. Sometimes the automatic stashing and popping the stash can lead to surprising results where you are not sure if the code-style has been applied or not.

These were the points of feedback I've gotten on the tool's aggressive nature. The feedback itself did not warrant to "throw out `lint-staged`", though it did make me think about the workflow.

#### Technical problems with `lint-staged`

The first real problem of `lint-staged` is that it needs to be the single entry-point for all validations. Which means that all `husky` does is call `lint-staged` with all staged files, then `lint-staged` figures out what to do with each file that was passed along.

That introduced the need for the `validate` command, that `husky` would call with configuration files to override settings for _all_ the tools. 

The `validate` command means that to add a new language checker, it also needed to be implemented in the `validate` command otherwise you could not use it in a git hook with other commands. As such, adding new language support is error prone and more difficult than it needs to be.

The way the call stack worked was also a mess of subprocesses:

- **`husky` execs `d2-style validate` execs `lint-staged` execs list of `d2-style <command> apply`**.

 The new call stack is much, much obvious:

- **`husky` execs a list of `d2style <command> check`**.

That new simplicity allows us to just drop-in new commands without wiring them from `validate` to `lint-staged` and on to the actual command.

With `lint-staged` we also had to maintain complete control of the configuration files we passed around, which required that the tools we used supported a NodeJS API that allowed us to override configuration files.

With the new style we can allow tools to find-up their own configuration files and only provide a default fallback.

This allows us to re-use Prettier to allow formatting for other formats that Prettier supports like HTML, Markdown, YAML, etc. without adding them to to the `javascript` command.

#### Architecture

> Or does it simply not fit into the new architecture and workflow you came up with so it was a "necessary" downgrade?

The piece that does not fit into the architecture and causes complications is the `validate` command. We added that to be able to get `lint-staged` to work at all.

The `validate` command was something I hoped we would be able to improve over time, but as I worked on adding support for e.g. Java and Markdown, I realized that while we could improve the code quality of `validate`, there is no way to fix the convoluted call stack and configuration that it causes. The `validate` command is a single point of failure and since it wraps the `lint-staged` NodeJS API it is also hard to test for consistency.

So to keep polyglot support, the `validate` command had to go. That has a ripple effect that `lint-staged` also needs to go.

#### Workflow

It is easy to argue both sides of the case for "only checking" or "always applying" for code standard compliance in a git hook but they both align under the same intent:

**The core rule is that code that violates the code style should not get committed.**

Our tools already have a concept of only running checks on all files or only on the staged files, and coupled with using pattern matching allows for the same kind of power that `lint-staged` gave us for linting staged files.

The main difference then is that by leveraging `lint-staged` we were able to lint specific hunks of staged files without worrying about stashing the unstaged hunks for files that has both staged **and** unstaged hunks.

A developer can still use the same workflow, but needs to do it manually:

```
git add -p
git stash
d2-style js apply --staged
git commit
git stash pop
```

All-in-all having a non-disruptive workflow by default ("only check for consistency") is a safer and more flexible approach for developers of all skill levels as it doesn't automatically cause changes that may or may not be expected.

**Comment by amcgee** [comment]
> Yes, I have received feedback that always applying the code style and automatically adding the formatted code back to the staged area is surprising to them. I think it _generally_ always works and does the right thing though, it's just a turn-off for some developers.

There have been some cases where it can make functional changes too, though - i.e. react-hooks/exhaustive-deps`

> A developer can still use the same workflow, but needs to do it manually:

This is great, and could be added to a local `precommit` git hook, so that it's not something "surprising" to the developer (since they explicitly did it)

**Comment by amcgee** [comment]
In general I really like this change, and it looks good!

Here are a few subtle (and not critical) challenges I encountered with the workflow:

1) It seems we lost some information about the number of files which were checked, I found this useful in the past because I wanted to be sure the tool was actually checking the files I expected - something like `Checked 18 staged javascript files` or `Checked 3 text files`, to indicate the number of files that matched the pattern (and whether or not we were checking staged files only).  When the tool runs automatically in a git hook it's not going to be obvious to a user what's actually going on.  We DO have this information in the `apply` command, albeit just in the 
2) The colors on the terminal and lack of any identifier for the "file" lines (maybe a `-` prefix?) make it very difficult to grep the output of the check command when there are files that need attention.
3) "Did you forget to run prettier?" maybe should be something like "run d2-style js apply" to fix
4) When installing the hooks for a JS project, only js files are checked (not structured text files) - shouldn't we check both?
5) There's no indication of WHAT broke the standards in each file, is it possible to expose the error output from the underlying tool?

Screenshot 2019-11-22 11 09 20

**Comment by varl** [comment]
> In general I really like this change, and it looks good!

Nice. 👍 

> Here are a few subtle (and not critical) challenges I encountered with the workflow:

Some of these are consequences of dropping the NodeJS API for the tools and reliance on the way the tools print information.

>     1. It seems we lost some information about the number of files which were checked, I found this useful in the past because I wanted to be sure the tool was actually checking the files I expected - something like `Checked 18 staged javascript files` or `Checked 3 text files`, to indicate the number of files that matched the pattern (and whether or not we were checking staged files only).  When the tool runs automatically in a git hook it's not going to be obvious to a user what's actually going on.  We DO have this information in the `apply` command, albeit just in the

This is information we still have access to, we can print that in a `reporter.info` message. Will fix. If you run with `--verbose` it prints all the matched files, but having just a quick reference for the count would be helpful.

>     2. The colors on the terminal and lack of any identifier for the "file" lines (maybe a `-` prefix?) make it very difficult to grep the output of the check command when there are files that need attention.

So this is actually how Prettier output looks:

```
varl@veronika:~/dev/dhis2/libs/cli-style$ npx prettier **/*.js --check
Checking formatting...
src/index.js
Code style issues found in the above file(s). Forgot to run Prettier?
```

So points: 2, 3 and 5 are related.

>     3. "Did you forget to run prettier?" maybe should be something like "run d2-style js apply" to fix

Since we no longer use the internal NodeJS API for Prettier we cannot easily convert the Prettier output to a custom report. Same point as above and is a consequence of _not_ using the NodeJS APIs for running tools like Prettier/ESLint.

We could probably use `--list-different` instead of `--check`: https://prettier.io/docs/en/cli.html#--list-different to get a list of incompatible files. I can see how it goes.
 
>     4. When installing the hooks for a JS project, only js files are checked (not structured text files) - shouldn't we check both?

So the `husky-frontend.local.js` hook does have that. The default husky config doesn't because of polyglot environments. The only constant is the commit check.

>     5. There's no indication of WHAT broke the standards in each file, is it possible to expose the error output from the underlying tool?

That's actually exactly what Prettier would print. Prettier doesn't let users know what parts of the Prettier configuration broke. It goes against their policy of "you should only care if it complies or not".

If you have a ESLint violation instead, we will print the full ESLint output:

```
./bin/d2-style js check src/utils/groups.js
d2-style > javascript

/home/varl/dev/dhis2/libs/cli-style/src/utils/groups.js
  267:29  error  'too' is defined but never used                                   no-unused-vars
  267:34  error  'many' is defined but never used                                  no-unused-vars
  267:40  error  'args' is defined but never used                                  no-unused-vars
  267:46  error  'foo' is defined but never used                                   no-unused-vars
  267:51  error  'bar' is defined but never used                                   no-unused-vars
  267:56  error  Arrow function has too many parameters (5). Maximum allowed is 3  max-params

✖ 6 problems (6 errors, 0 warnings)
```

**Comment by varl** [comment]
Updated the log messages a bit:

```bash
git commit
husky > pre-commit (node v10.17.0)
d2-style > javascript
Checking formatting...
All matched files use Prettier code style!
Checked javascript 1 file(s)
d2-style > structured-text
No matching staged text files for pattern "**/*.{md,json,yml,html}"
husky > commit-msg (node v10.17.0)
d2-style > commit
[husky 12a0761] refactor: make the log a bit more specific
 Date: Fri Nov 22 15:17:16 2019 +0100
 3 files changed, 6 insertions(+), 4 deletions(-)
```

**Comment by varl** [comment]
@amcgee I changed around some bits and pieces so now the Prettier logs should look a bit better. Addressed 2 and 3.

**Comment by amcgee** [comment]
Nice, tested, really like the updated messaging!  I had one additional concern which we may not be able to avoid (just getting up to speed here) but otherwise this looks really good 👍 

---

I realize this is probably the main drawback of this change, but I didn’t fully appreciate it until just now -

1. I try to `git commit` something that violates the standards, correctly get an error, and the commit fails (saying **run “d2-style js apply” to fix**)
2. Then I run `d2-style js apply` and it fixes the problem, but doesn’t stage the file
3. I run `git commit` again, the checks pass and the commit succeeds but still with the “bad” contents since I never ran `git add`.

This seems error-prone, but maybe we can’t avoid it?

Also - I just realized that the message run “d2-style js apply” to fix makes the assumption that d2-style is installed globally, which it might not be…

**Comment by varl** [comment]
> Also - I just realized that the message run “d2-style js apply” to fix makes the assumption that d2-style is installed globally, which it might not be…

Yeah, helpful messages are _hard_. Maybe we can just skip the command suggestion and say that they need to use the "apply" command?

**Comment by varl** [comment]
> I realize this is probably the main drawback of this change, but I didn’t fully appreciate it until just now

Yeah, this is what `lint-staged` gave us for "free".

We can run `git add .` as a task in `.huskyrc.js` after formatting, but then we break the hunks workflow.

Even if we just re-add the staged files after they've been formatted, they might still contain hunks so we would have to figure out how to stage hunks of files after formatting. `lint-staged` solution to this is quite involved, and we have tried implementing a simpler version of it but there were too many edge cases.

The good enough option is to cede control to the developer after she reformats files. We could put a message reminding the dev to git add the changes but it is a bit "eh".

**Comment by amcgee** [comment]
Yeah these are both tough...

Would it be too disruptive to detect **any** unstaged files, cancel the commit, and say "please stash your changes before committing" ?

**Comment by varl** [comment]
>Would it be too disruptive to detect any unstaged files, cancel the commit, and say "please stash your changes before committing" ?

Yeah, I think that is pretty harsh.

We run the style check again on CI, so at worst someone will have to amend and force-push, or commit a style-fix commit.

[We do support the `style:` prefix](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) which gets ignored in changelogs.

**Pull request merged**
