### PR TITLE
chore: release alpha

### PR DESCRIPTION
**Pull request by ismay**
@HendrikThePendric mentioned here: https://github.com/dhis2/ui/pull/580 that there are changes on cli-style@alpha that fix the editor integration for eslint. @varl and I were looking at the alpha branch a while back (see here: https://github.com/dhis2/scheduler-app/pull/174). I've taken a look, and from my perspective the only things that came up there that we hadn't addressed yet are:

- Set D2_VERBOSE to false for default workflows to clean up logging on CI: https://github.com/dhis2/workflows/blob/master/ci/dhis2-verify-app.yml#L12 (PR here: https://github.com/dhis2/workflows/pull/9)
- Disable pre push jest tests by default (later on investigate if adding https://jestjs.io/docs/next/cli#--lastcommit to the default pre commit hook would be possible) (✅ done)
- Investigate ls-lint conflict between kebabcase and pointcase for test files and similarly named files (pointcase is seen as a violation of the kebabcase rule)

The workflow change doesn't have to be addressed in cli-style, and the other two aren't critical in my opinion. I think we could merge alpha to master as far as I'm concerned (all critical things I could find during testing are fixed). What do you think @varl?

### CODE REVIEW

**Comment by varl** [comment]
> Disable pre push jest tests by default

This is done, I believe. We only add the `commit-msg` and `pre-commit` hooks by default.

**Comment by varl** [comment]
> Investigate ls-lint conflict between kebabcase and pointcase for test files and similarly named files

The workaround is to specify all the "sub-extensions", e.g.:

`.spec.js: kebab-case`

**Review by varl — APPROVED** [review]

**Comment by ismay** [comment]
> > Disable pre push jest tests by default
> 
> This is done, I believe. We only add the `commit-msg` and `pre-commit` hooks by default.

Ah yeah you're right. 👍

**Comment by ismay** [comment]
> There are a few workarounds, but we can deal with those in a separate PR as ls-lint needs to be added manually to a project anyway.

I checked it out thinking it would be a quick fix, but I couldn't really find a decent way to quickly address it. I'll create an issue for it.

**Pull request merged**
