### PR TITLE
feat(renovate): add renovate configuration setup

### PR DESCRIPTION
**Pull request by varl**
Configuration files shared for the organisation:

- Default config: https://github.com/dhis2/.github/blob/master/default.json
- On-boarding config for repos: https://github.com/dhis2/.github/blob/master/renovate-config.json

### CODE REVIEW

**Comment by varl** [comment]
@ismay trying out Renovate in CLI Style atm, figured you might be interested in this.

**Comment by ismay** [comment]
Ah nice

**Comment by ismay** [comment]
Did the defaults not work for us btw? I've found those to work quite well

**Comment by varl** [comment]
> Did the defaults not work for us btw? I've found those to work quite well

Mostly. The `default` settings are added explicitly instead of referencing the base setup. The reason for that is that the default may change upstream and would be automatically rolled out to us on the next run. If we are going to automerge as much as possible, we need a stable configuration that doesn't change without our intent.

The modifications to the defaults are:

- `[:pinOnlyDevDependencies](https://github.com/dhis2/.github/blob/master/default.json#L10)` The config-app and config-lib defaults are different, so to avoid autodetecting the wrong deps to pin, this is set explicitly.
- `[autoMergeType=branch](https://github.com/dhis2/.github/blob/master/default.json#L17)` Avoid a PR if everything on the branch works. Need to run CI on branches, not PRs (which we do).
- `[lockFileMaintenance](https://github.com/dhis2/.github/blob/master/default.json#L18-L21)` We can automerge lockfile maintenance.
- `[rebaseWhen=behind-base-branch](https://github.com/dhis2/.github/blob/master/default.json#L22)` Use rebase when behind base.
- `[packageRules](https://github.com/dhis2/.github/blob/master/default.json#L23)`
  - Add rules for our monorepo packages so they can be grouped.
  - Allow code style to be run after bumping cli-style.
  - Automerge patch and minor updates.

**Comment by ismay** [comment]
> > Did the defaults not work for us btw? I've found those to work quite well
> 
> Mostly. The `default` settings are added explicitly instead of referencing the base setup. The reason for that is that the default may change upstream and would be automatically rolled out to us on the next run. If we are going to automerge as much as possible, we need a stable configuration that doesn't change without our intent.
> 
> The modifications to the defaults are:
> 
>     * [`:pinOnlyDevDependencies`](https://github.com/dhis2/.github/blob/master/default.json#L10) The config-app and config-lib defaults are different, so to avoid autodetecting the wrong deps to pin, this is set explicitly. Eventually, we'd like to move this back to default.
> 
>     * [`autoMergeType=branch`](https://github.com/dhis2/.github/blob/master/default.json#L17) Avoid a PR if everything on the branch works. Need to run CI on branches, not PRs (which we do).
> 
>     * [`lockFileMaintenance`](https://github.com/dhis2/.github/blob/master/default.json#L18-L21) We can automerge lockfile maintenance.
> 
>     * [`rebaseWhen=behind-base-branch`](https://github.com/dhis2/.github/blob/master/default.json#L22) Use rebase when behind base.
> 
>     * [`packageRules`](https://github.com/dhis2/.github/blob/master/default.json#L23)
>       
>       * Add rules for our monorepo packages so they can be grouped.
>       * Allow code style to be run after bumping cli-style.
>       * Automerge patch and minor updates.

I see, yeah that makes sense. I'm a _little_ apprehensive about automerging without something like say a couple visual regression tests in place (on top of a decent unit/e2e test suite), but then again automerging would really cut down on manual maintenance. So maybe it can just be an incentive for us to prioritize rolling out proper test suites across all of our repos.

**Review by ismay — APPROVED** [review]

**Comment by varl** [comment]
Agreed, it's a bit out of the comfort zone. We can always override the settings in apps/libs where automerging is too aggressive, or change to getting a PR per dep update.

I think we'll get to a better place if we have a policy of requiring _at least_ a smoke test to adopt Renovate in an app/lib instead of rolling it out everywhere and "eventually" adding test.

Related: https://github.com/dhis2/notes/issues/71

**Comment by ismay** [comment]
> I think we'll get to a better place if we have a policy of requiring at least a smoke test to adopt Renovate in an app/lib instead of rolling it out everywhere and "eventually" adding test.

Yeah that sounds like a good requirement

**Pull request merged**
