### PR TITLE
fix: wrong hooks where installed by default

### PR DESCRIPTION
**Pull request by varl**

### CODE REVIEW

**Review by ismay — COMMENTED** [review]
This hasn't fixed it for me. If I use the d2-style on this branch, and then run `d2-style install`, it still installs the hooks that can be found here: https://github.com/dhis2/cli-style/tree/alpha/.hooks

**Comment by ismay** [comment]
Maybe I'm doing it wrong? I see it accepts a `--config` flag. I'm not passing that though. So since I'm not passing that it seems to default to the one in cli-style. Is the user expected to have and pass a `d2-style.config.js`?

**Comment by varl** [comment]
> Maybe I'm doing it wrong? I see it accepts a `--config` flag. I'm not passing that though. So since I'm not passing that it seems to default to the one in cli-style. Is the user expected to have and pass a `d2-style.config.js`?

No, that isn't necessary.

**Comment by varl** [comment]
> This hasn't fixed it for me. If I use the d2-style on this branch, and then run `d2-style install`, it still installs the hooks that can be found here: https://github.com/dhis2/cli-style/tree/alpha/.hooks

How are you running this branch in another project? Are you using e.g. `/path/to/cli-style/bin/d2-style install` or a yarn link followed by `yarn d2-style install` ?

**Comment by varl** [comment]
Ah, @ismay. I found it. 1fc1c04

We were resolving the d2style config in relation to the package (cli-style), and not the project (cwd).

**Comment by ismay** [comment]
> Ah, @ismay. I found it. [1fc1c04](https://github.com/dhis2/cli-style/commit/1fc1c0420d6102e4f4e2d7ea9eb28e34cfdaa5ed)
> 
> We were resolving the d2style config in relation to the package (cli-style), and not the project (cwd).

That seems to have done it, both hooks work for me locally after this fix and a clean install.

> How are you running this branch in another project? Are you using e.g. /path/to/cli-style/bin/d2-style install or a yarn link followed by yarn d2-style install ?

I was testing it by running `y add --dev git+https://github.com/dhis2/cli-style#wrong-hooks-installed` and then an `npx d2-style install --clean`

**Review by ismay — APPROVED** [review]

**Pull request merged**
