### PR TITLE
fix: make the messages more meaningful

### LINKED ISSUE #24: "No files to style" message
The feedback I get when I check all my files:

screenshot 2019-03-06 at 17 26 14

Might lead one to believe that you didn't pass any files. When I'm assuming that this is meant to indicate that all checked files are ok. Or am I wrong in assuming that? I was expecting `--all` to check all js in the project.

### PR DESCRIPTION
**Pull request by varl**
Fixes #24

### CODE REVIEW

**Comment by varl** [comment]
```
.../dhis2/libs/cli-style > ./bin/d2-style js check
No staged files found. 
No files to check. 

.../dhis2/libs/cli-style > ./bin/d2-style js check --all
Files to style: 
src/cmds/js_cmds/check.js 
 
[ERROR] 1 file(s) failed the style check 

.../dhis2/libs/cli-style ! > ./bin/d2-style js apply
No staged files found. 
No files to format. 
Stage 0 file(s). 

.../dhis2/libs/cli-style > ./bin/d2-style js apply --all
Reformatted: /home/varl/dev/dhis2/libs/cli-style/src/cmds/js_cmds/check.js 
Stage 1 file(s). 
Staging /home/varl/dev/dhis2/libs/cli-style/src/cmds/js_cmds/check.js... 
```

**Comment by ismay** [comment]
Ah nice. So what would I get now with `.../dhis2/libs/cli-style > ./bin/d2-style js check --all` when it's checked all files and they're all fine?

I like the way lint-staged does it for example:

screenshot 2019-03-07 at 13 41 08

If everything's fine it clearly shows you which checks it ran, and that everything succeeded.

**Comment by varl** [comment]
I missed that case:

```
.../dhis2/libs/cli-style ! > ./bin/d2-style js check --all
15 file(s) passed the style check. 
```

**Comment by varl** [comment]
We are going to take a look at general guidelines for how we should present output from `d2` command modules so we are just trying to get the messages good enough for now. Eventually we want to make the output consistent and nice between all `d2` commands and modules.

**Comment by ismay** [comment]
> .../dhis2/libs/cli-style ! > ./bin/d2-style js check --all
> 15 file(s) passed the style check. 

Nice, yeah that's what I expected 👍

**Pull request merged**
