### PR TITLE
fix: ignore .yarn directory

### PR DESCRIPTION
**Pull request by varl**

### CODE REVIEW

**Review by HendrikThePendric — APPROVED** [review]

**Comment by HendrikThePendric** [comment]
I'll update https://github.com/dhis2/ui/pull/580 once this gets released.

**Comment by ismay** [comment]
I think we don't need this fix actually. I had forgotten that there are ignores for `.yarn` in [./.eslintignore](https://github.com/dhis2/ui/pull/580/files#diff-a0fdacd2ade87c5238dde44378f574f7e123e669acdf8b740878b14b33b20275R1) and [./.prettierignore](https://github.com/dhis2/ui/pull/580/files#diff-b640b344ee7f3f03d2a443795a5d0708ef50e2e6e34214109ab2aad13ad6ba98R1). So cli-style's behaviour is correct here: it's warning us that we're passing it something we've ignored.

I think the actual problem here is that it makes sense to ignore the `.yarn` dir in ui. But then we either need a mechanism in cli-style that will omit ignored files when you run `d2-style apply` without any file arguments, or we need to pass a more specific glob to d2-style in ui which omits .yarn so that `d2-style` won't log the warning.

**Comment by ismay** [comment]
Now that I think about it, I don't think we need this fix actually. I had forgotten that there are ignores for `.yarn` in [./.eslintignore](https://github.com/dhis2/ui/pull/580/files#diff-a0fdacd2ade87c5238dde44378f574f7e123e669acdf8b740878b14b33b20275R1) and [./.prettierignore](https://github.com/dhis2/ui/pull/580/files#diff-b640b344ee7f3f03d2a443795a5d0708ef50e2e6e34214109ab2aad13ad6ba98R1). So cli-style's behaviour is correct here: it's warning us that we're passing it something we've ignored.

I think the actual problem here is that we've explicitly ignored the `.yarn` dir in ui, but the `d2-style apply` command we're running in ui will match files in `.yarn` and pass them to eslint. So I suspect we either need:

1. A mechanism in cli-style that will omit ignored files when you run `d2-style apply` without any file arguments. So that linters don't receive ignored files
2. Or, we need to pass a more specific glob to `d2-style` in `ui`, which omits `.yarn` so that `d2-style` won't log the warning.

---

edit: Actually, I'm wondering now if this PR does exactly what I'm mentioning in 1. If so, then consider this another roundabout way of me being on board with the suggested changes 😅👍

**Comment by varl** [comment]
> A mechanism in cli-style that will omit ignored files when you run d2-style apply without any file arguments. So that linters don't receive ignored files

This is what this does: https://github.com/dhis2/cli-style/blob/master/src/utils/files.js#L9-L19

**Comment by varl** [comment]
This does fix the problem, so I'm going ahead with releasing it.

**Pull request merged**
